version: '3'

services:

  grafana:
    image: grafana/grafana:8.5.2
    container_name: tatarincevaa-netology-grafana
    ports:
      - 80:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-config:/etc/grafana
      - ./grafana/custom.ini:/etc/grafana/custom.ini
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/custom.ini
    restart: always

volumes:
  grafana-data:
  grafana-config:
