version: '3'
services:
  pushgateway:
    image: prom/pushgateway:v1.6.2
    container_name: tatarincevaapushgateway
    ports:
     - 9091:9091
    networks:
     - monitoring-stack
    depends_on:
     - prometheus
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: tatarincevaaprometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    ports:
     - 9090:9090
    volumes:
     - ./prometheus:/etc/prometheus
     - prometheus-data:/prometheus
    networks:
     - monitoring-stack
    restart: always

volumes:
  prometheus-data:

networks:
  monitoring-stack:
    name: TatarincevAlexeyAlexeevich-my-netology-hw
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
